# Generated by Django 4.0.4 on 2022-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre de Producto'),
        ),
    ]
