# Generated by Django 4.0.4 on 2022-10-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_product_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='costo',
            field=models.FloatField(verbose_name='Costo de compra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.FloatField(verbose_name='Precio de venta'),
        ),
    ]
