# Generated by Django 4.0.4 on 2022-10-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_product_costo_alter_product_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actualizar',
            field=models.BooleanField(default=True, verbose_name='Actualizar producto'),
        ),
    ]
